### ISSUE TITLE
It's not possible to export modules defined in base java

### ISSUE THREAD

**Issue by denisfalqueto** [meterware/multirelease-parent#1]
When compiling for java 9+, the compiler can't find original modules, so it throws these messages:

    error: package is empty or does not exist: <pkg.name.etc>

The package exists in my src/main/java directory, but the execution for java 9+ can't see them.

**Comment by russgold** [comment]
It's been working for me, so there would seem to be something different about your setup. How can I duplicate this? Can you make a repo on which it happens available to me?

**Comment by denisfalqueto** [comment]
I'll send a pull request with changes that made it work here.

**Comment by denisfalqueto** [comment]
Would you mind publishing a new release?

**Comment by russgold** [comment]
Sure. I might as well add jdk12 and jdk13, as they are in ea now.

**Comment by denisfalqueto** [comment]
Perfect! Thank you so much for marinating this project! It saved me a lot of work.
