### ISSUE TITLE
It worked, but replaced due to issues using alternate source paths and many profiles

### ISSUE THREAD

**Issue by rwperrott** [meterware/multirelease-parent#3]
This worked for building one of my libraries, via rolling into my own parent POM, with mods, but using other source paths can conflict with IDE Java-version source code validation and editing assistance, I also disliked the clutter of many Java version profiles.  I expect the same issues with multi-release Maven plugins too, like (https://github.com/metlos/multi-release-jar-maven-plugin)

I have replaced it in my projects with an approach based on (https://word-bits.flurg.com/multrelease-jars/), even if it is slower, because it is uses a separate standard Maven project for each Java version, with standard unit test support, via:
- a parent pom for the multi-release library, with an artifactId like {library-name}-mr, declaring any dependencies needed by the base Java version.
- a module project for the base Java version, with an artifactId like {library-name}-8, with toolchain declaration.
- a module project for each Java 9+ overlay, with an artifactId like {library-name}-{java-version}, each with a dependency on the base Java version module, with toolchain declaration.
- a module project with dependencies declared for all the Java version module projects, so that these can be separately unpacked during the "generate-resources phase" using "maven-dependency-plugin" into ${project.build.directory}/generated-resources/ for the base version and ${project.build.directory}/generated-resources/version/{java-version-number} for the rest, so that "maven-jar-plugin" can assemble the jar during the "package" phase.

**Comment by RichardWPerrott** [comment]
I discovered a snag with my approach, and a workaround; my assembler module project has to declare the version modules as "test" scope and do the assembly in the "test" phase, to avoid leaking the dependencies.

**Comment by RichardWPerrott** [comment]
Looks like my approach has issues too, so I can see why yours took some work.

**Comment by RichardWPerrott** [comment]
I cracked the flaws with the approach at (https://word-bits.flurg.com/multrelease-jars/), by removing the resources element, stop extracting anything to target/generated-resources and used maven-dependency-plugin with executions to
- send base **/*.class to ${project.build.directory}/classes
- send base **.*.java to ${project.build.directory}/generated-sources
- send each other **/*.class to ${project.build.directory}/classes/META-INF/versions/{version}
- send each other **.*.java to ${project.build.directory}/generated-sources/META-INF/versions/{version}
* I guess that is the correct source structure
I changed the dependencies to have also have `<optional>true</optional>` and added:
```xml
<plugin>
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-jar-plugin</artifactId>
      <configuration>
         <archive>
            <manifestEntries>
                <Multi-Release>true</Multi-Release>
            </manifestEntries>
           </archive>
      </configuration>
</plugin>
```

**Comment by RichardWPerrott** [comment]
and added
```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifestEntries>
                            <Multi-Release>true</Multi-Release>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
```

**Comment by rwperrott** [comment]
Lost interest.
